import path from 'node:path';
import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { settings, defineValue, processAssets } from './shared.js';
export default function esbuild(options) {
  const resolved = settings(options);
  return {
    name: 'siteqwality-esbuild',
    setup(build) {
      const input = build.initialOptions;
      if (!input.outdir && !input.outfile)
        throw new Error('SiteQwality requires esbuild outdir or outfile');
      if (input.sourcemap === 'inline' || input.sourcemap === 'both')
        throw new Error('SiteQwality requires external esbuild source maps');
      const shouldWrite = input.write !== false;
      // Work on final generated bytes before disk writes, including write:false builds.
      input.write = false;
      input.sourcemap ||= true;
      input.define = { ...input.define, __SQ_RELEASE__: defineValue(resolved) };
      const cwd = input.absWorkingDir || process.cwd();
      const root = path.resolve(cwd, input.outdir || path.dirname(input.outfile));
      build.onEnd(async (result) => {
        if (result.errors.length) return;
        const names = new Map();
        const assets = new Map();
        for (const file of result.outputFiles || []) {
          const name = path.relative(root, file.path).split(path.sep).join('/');
          names.set(name, file);
          assets.set(name, file.text);
        }
        const { edits, remove } = await processAssets(assets, resolved);
        for (const [name, text] of edits) {
          const file = names.get(name);
          file.contents = new TextEncoder().encode(text);
          file.hash = createHash('sha256').update(file.contents).digest('hex');
        }
        result.outputFiles = (result.outputFiles || []).filter(
          (file) => !remove.includes(path.relative(root, file.path).split(path.sep).join('/')),
        );
        if (result.metafile) {
          const finalFiles = new Map(result.outputFiles.map((file) => [file.path, file]));
          for (const [file, metadata] of Object.entries(result.metafile.outputs)) {
            const output = finalFiles.get(path.resolve(cwd, file));
            if (output) metadata.bytes = output.contents.byteLength;
            else delete result.metafile.outputs[file];
          }
        }
        if (shouldWrite)
          for (const file of result.outputFiles) {
            await mkdir(path.dirname(file.path), { recursive: true });
            await writeFile(file.path, file.contents, {
              mode: file.text.startsWith('#!') ? 0o755 : 0o644,
            });
          }
      });
    },
  };
}
